"""initial schema: 13 tables

Revision ID: 046d37447ab0
Revises:
Create Date: 2026-02-12 17:04:35.427933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "046d37447ab0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("ats_platform", sa.String(length=50), nullable=False),
        sa.Column("career_site_url", sa.Text(), nullable=False),
        sa.Column("scraper_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "markets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("dma", sa.String(length=255), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "retailers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("channel_type", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "agg_brand_timeline",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_currently_active", sa.Boolean(), nullable=False),
        sa.Column("total_postings_all_time", sa.Integer(), nullable=False),
        sa.Column("current_active_postings", sa.Integer(), nullable=False),
        sa.Column("peak_active_postings", sa.Integer(), nullable=False),
        sa.Column("peak_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_brand_timeline_company_brand",
        "agg_brand_timeline",
        ["company_id", "brand_id"],
        unique=False,
    )
    op.create_table(
        "agg_daily_velocity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("market_id", sa.UUID(), nullable=True),
        sa.Column("active_postings", sa.Integer(), nullable=False),
        sa.Column("new_postings", sa.Integer(), nullable=False),
        sa.Column("closed_postings", sa.Integer(), nullable=False),
        sa.Column("net_change", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_velocity_date_company", "agg_daily_velocity", ["date", "company_id"], unique=False
    )
    op.create_table(
        "agg_pay_benchmarks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("role_archetype", sa.String(length=100), nullable=True),
        sa.Column("market_id", sa.UUID(), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("avg_pay_min", sa.Float(), nullable=True),
        sa.Column("avg_pay_max", sa.Float(), nullable=True),
        sa.Column("median_pay_min", sa.Float(), nullable=True),
        sa.Column("median_pay_max", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agg_posting_lifecycle",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("role_archetype", sa.String(length=100), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("market_id", sa.UUID(), nullable=True),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("avg_days_open", sa.Float(), nullable=True),
        sa.Column("median_days_open", sa.Float(), nullable=True),
        sa.Column("repost_rate", sa.Float(), nullable=True),
        sa.Column("avg_repost_gap_days", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "postings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("external_job_id", sa.String(length=255), nullable=True),
        sa.Column("fingerprint_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("times_reposted", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_postings_brand_active", "postings", ["company_id", "is_active"], unique=False
    )
    op.create_index("ix_postings_fingerprint_hash", "postings", ["fingerprint_hash"], unique=False)
    op.create_table(
        "posting_brand_mentions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("entity_name", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("resolved_brand_id", sa.UUID(), nullable=True),
        sa.Column("resolved_retailer_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["postings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posting_enrichments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=True),
        sa.Column("role_archetype", sa.String(length=100), nullable=True),
        sa.Column("role_level", sa.String(length=50), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("retailer_id", sa.UUID(), nullable=True),
        sa.Column("market_id", sa.UUID(), nullable=True),
        sa.Column("pay_type", sa.String(length=50), nullable=True),
        sa.Column("pay_min", sa.Float(), nullable=True),
        sa.Column("pay_max", sa.Float(), nullable=True),
        sa.Column("pay_currency", sa.String(length=3), nullable=True),
        sa.Column("pay_frequency", sa.String(length=20), nullable=True),
        sa.Column("commission_mentioned", sa.Boolean(), nullable=True),
        sa.Column("commission_details", sa.Text(), nullable=True),
        sa.Column("benefits_mentioned", sa.Boolean(), nullable=True),
        sa.Column("benefits_summary", sa.Text(), nullable=True),
        sa.Column("content_role_specific", sa.Text(), nullable=True),
        sa.Column("content_boilerplate", sa.Text(), nullable=True),
        sa.Column("content_qualifications", sa.Text(), nullable=True),
        sa.Column("content_responsibilities", sa.Text(), nullable=True),
        sa.Column("tools_mentioned", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("kpis_mentioned", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("store_count_mentioned", sa.Integer(), nullable=True),
        sa.Column("travel_required", sa.Boolean(), nullable=True),
        sa.Column("employment_type", sa.String(length=50), nullable=True),
        sa.Column("enrichment_model", sa.String(length=100), nullable=True),
        sa.Column("enrichment_version", sa.String(length=50), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["postings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posting_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("title_raw", sa.Text(), nullable=True),
        sa.Column("location_raw", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("full_text_raw", sa.Text(), nullable=True),
        sa.Column("full_text_hash", sa.String(length=64), nullable=True),
        sa.Column("content_changed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["postings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_snapshots_company_brand_date",
        "posting_snapshots",
        ["posting_id", "snapshot_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshots_company_brand_date", table_name="posting_snapshots")
    op.drop_table("posting_snapshots")
    op.drop_table("posting_enrichments")
    op.drop_table("posting_brand_mentions")
    op.drop_index("ix_postings_fingerprint_hash", table_name="postings")
    op.drop_index("ix_postings_brand_active", table_name="postings")
    op.drop_table("postings")
    op.drop_table("agg_posting_lifecycle")
    op.drop_table("agg_pay_benchmarks")
    op.drop_index("ix_velocity_date_company", table_name="agg_daily_velocity")
    op.drop_table("agg_daily_velocity")
    op.drop_index("ix_brand_timeline_company_brand", table_name="agg_brand_timeline")
    op.drop_table("agg_brand_timeline")
    op.drop_table("users")
    op.drop_table("retailers")
    op.drop_table("markets")
    op.drop_table("companies")
    op.drop_table("brands")
    # ### end Alembic commands ###
