// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BrandMentionDetail
 */
export type BrandMentionDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Brand Id
     */
    brand_id: string | null;
    /**
     * Brand Name
     */
    brand_name: string | null;
    /**
     * Entity Name
     */
    entity_name: string;
    /**
     * Entity Type
     */
    entity_type: string;
    /**
     * Confidence Score
     */
    confidence_score: number | null;
};

/**
 * CompanyResultResponse
 */
export type CompanyResultResponse = {
    /**
     * Company Slug
     */
    company_slug: string;
    /**
     * Postings Found
     */
    postings_found: number;
    /**
     * Snapshots Created
     */
    snapshots_created: number;
    /**
     * Errors
     */
    errors: Array<string>;
    /**
     * Warnings
     */
    warnings: Array<string>;
    /**
     * Success
     */
    success: boolean;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * ComparisonCreate
 */
export type ComparisonCreate = {
    /**
     * Posting Id
     */
    posting_id: string;
    /**
     * Result A Id
     */
    result_a_id: string;
    /**
     * Result B Id
     */
    result_b_id: string;
    /**
     * Winner
     */
    winner: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * EnrichCurrentRun
 */
export type EnrichCurrentRun = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Pass1 Total
     */
    pass1_total: number;
    /**
     * Pass1 Succeeded
     */
    pass1_succeeded: number;
    /**
     * Pass1 Skipped
     */
    pass1_skipped?: number;
    /**
     * Pass2 Total
     */
    pass2_total: number;
    /**
     * Pass2 Succeeded
     */
    pass2_succeeded: number;
    /**
     * Pass2 Skipped
     */
    pass2_skipped?: number;
};

/**
 * EnrichResultResponse
 */
export type EnrichResultResponse = {
    /**
     * Succeeded
     */
    succeeded: number;
    /**
     * Failed
     */
    failed: number;
    /**
     * Skipped
     */
    skipped: number;
};

/**
 * EnrichmentDetail
 */
export type EnrichmentDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Title Normalized
     */
    title_normalized: string | null;
    /**
     * Role Archetype
     */
    role_archetype: string | null;
    /**
     * Role Level
     */
    role_level: string | null;
    /**
     * Pay Type
     */
    pay_type: string | null;
    /**
     * Pay Min
     */
    pay_min: number | null;
    /**
     * Pay Max
     */
    pay_max: number | null;
    /**
     * Pay Currency
     */
    pay_currency: string | null;
    /**
     * Pay Frequency
     */
    pay_frequency: string | null;
    /**
     * Employment Type
     */
    employment_type: string | null;
    /**
     * Commission Mentioned
     */
    commission_mentioned: boolean | null;
    /**
     * Benefits Mentioned
     */
    benefits_mentioned: boolean | null;
    /**
     * Enrichment Version
     */
    enrichment_version: string | null;
    /**
     * Enriched At
     */
    enriched_at: string | null;
};

/**
 * EnrichmentRunResponse
 */
export type EnrichmentRunResponse = {
    /**
     * Run Id
     */
    run_id: string;
    status: EnrichmentStatus;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    pass1_result: EnrichResultResponse | null;
    pass2_result: EnrichResultResponse | null;
    /**
     * Total Input Tokens
     */
    total_input_tokens?: number;
    /**
     * Total Output Tokens
     */
    total_output_tokens?: number;
    /**
     * Total Api Calls
     */
    total_api_calls?: number;
    /**
     * Total Dedup Saved
     */
    total_dedup_saved?: number;
    /**
     * Circuit Breaker Tripped
     */
    circuit_breaker_tripped?: boolean;
    /**
     * Error Summary
     */
    error_summary?: string | null;
};

/**
 * EnrichmentRunSummary
 */
export type EnrichmentRunSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Pass1 Total
     */
    pass1_total: number;
    /**
     * Pass1 Succeeded
     */
    pass1_succeeded: number;
    /**
     * Pass2 Total
     */
    pass2_total: number;
    /**
     * Pass2 Succeeded
     */
    pass2_succeeded: number;
};

/**
 * EnrichmentStatus
 */
export type EnrichmentStatus = 'pending' | 'running' | 'success' | 'partial' | 'failed';

/**
 * FieldReviewCreate
 */
export type FieldReviewCreate = {
    /**
     * Result Id
     */
    result_id: string;
    /**
     * Field Name
     */
    field_name: string;
    /**
     * Model Value
     */
    model_value: string | null;
    /**
     * Is Correct
     */
    is_correct: -1 | 0 | 1;
    /**
     * Correct Value
     */
    correct_value?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InviteRequest
 */
export type InviteRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role?: 'admin' | 'viewer';
};

/**
 * InviteResponse
 */
export type InviteResponse = {
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role: string;
    /**
     * Invited
     */
    invited: boolean;
};

/**
 * PipelineRunListResponse
 */
export type PipelineRunListResponse = {
    /**
     * Runs
     */
    runs: Array<PipelineRunSummary>;
    /**
     * Total
     */
    total: number;
};

/**
 * PipelineRunResponse
 */
export type PipelineRunResponse = {
    /**
     * Run Id
     */
    run_id: string;
    status: PipelineStatus;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Total Postings Found
     */
    total_postings_found: number;
    /**
     * Total Snapshots Created
     */
    total_snapshots_created: number;
    /**
     * Total Errors
     */
    total_errors: number;
    /**
     * Companies Succeeded
     */
    companies_succeeded: number;
    /**
     * Companies Failed
     */
    companies_failed: number;
    /**
     * Company Results
     */
    company_results: {
        [key: string]: CompanyResultResponse;
    };
    /**
     * Company States
     */
    company_states: {
        [key: string]: string;
    };
};

/**
 * PipelineRunSummary
 */
export type PipelineRunSummary = {
    /**
     * Run Id
     */
    run_id: string;
    status: PipelineStatus;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Total Postings Found
     */
    total_postings_found: number;
    /**
     * Total Snapshots Created
     */
    total_snapshots_created: number;
    /**
     * Companies Succeeded
     */
    companies_succeeded: number;
    /**
     * Companies Failed
     */
    companies_failed: number;
};

/**
 * PipelineRunsResponse
 */
export type PipelineRunsResponse = {
    /**
     * Scrape Runs
     */
    scrape_runs: Array<ScrapeRunSummary>;
    /**
     * Enrichment Runs
     */
    enrichment_runs: Array<EnrichmentRunSummary>;
};

/**
 * PipelineStatus
 *
 * Overall status of a pipeline run.
 */
export type PipelineStatus = 'pending' | 'running' | 'paused' | 'stopping' | 'success' | 'partial' | 'failed' | 'cancelled';

/**
 * PipelineStatusResponse
 */
export type PipelineStatusResponse = {
    /**
     * System State
     */
    system_state: string;
    scrape: StageStatus;
    enrich: StageStatus;
    scheduler: SchedulerSummary;
};

/**
 * PostingDetailResponse
 */
export type PostingDetailResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Company Id
     */
    company_id: string;
    /**
     * External Job Id
     */
    external_job_id: string | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * Location
     */
    location: string | null;
    /**
     * Url
     */
    url: string | null;
    /**
     * First Seen At
     */
    first_seen_at: string;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Times Reposted
     */
    times_reposted: number;
    enrichment: EnrichmentDetail | null;
    /**
     * Brand Mentions
     */
    brand_mentions: Array<BrandMentionDetail>;
};

/**
 * PostingListItem
 */
export type PostingListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Company Id
     */
    company_id: string;
    /**
     * Company Name
     */
    company_name: string | null;
    /**
     * Company Slug
     */
    company_slug: string | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * Location
     */
    location: string | null;
    /**
     * First Seen At
     */
    first_seen_at: string;
    /**
     * Last Seen At
     */
    last_seen_at: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Role Archetype
     */
    role_archetype: string | null;
    /**
     * Pay Min
     */
    pay_min: number | null;
    /**
     * Pay Max
     */
    pay_max: number | null;
    /**
     * Pay Currency
     */
    pay_currency: string | null;
    /**
     * Employment Type
     */
    employment_type: string | null;
};

/**
 * PostingListResponse
 */
export type PostingListResponse = {
    /**
     * Items
     */
    items: Array<PostingListItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * RunCreate
 */
export type RunCreate = {
    /**
     * Pass Number
     */
    pass_number: number;
    /**
     * Model
     */
    model: string;
    /**
     * Prompt Version
     */
    prompt_version: string;
    /**
     * Concurrency
     */
    concurrency?: number;
};

/**
 * ScheduleInfo
 */
export type ScheduleInfo = {
    /**
     * Schedule Id
     */
    schedule_id: string;
    /**
     * Next Fire Time
     */
    next_fire_time: string | null;
    /**
     * Last Fire Time
     */
    last_fire_time: string | null;
    /**
     * Paused
     */
    paused: boolean;
};

/**
 * SchedulerStatusResponse
 */
export type SchedulerStatusResponse = {
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Schedules
     */
    schedules: Array<ScheduleInfo>;
    /**
     * Last Pipeline Finished At
     */
    last_pipeline_finished_at: string | null;
    /**
     * Last Pipeline Success
     */
    last_pipeline_success: boolean;
    /**
     * Missed Run
     */
    missed_run: boolean;
};

/**
 * SchedulerSummary
 */
export type SchedulerSummary = {
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Next Run At
     */
    next_run_at: string | null;
};

/**
 * ScrapeCurrentRun
 */
export type ScrapeCurrentRun = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Total Postings Found
     */
    total_postings_found: number;
    /**
     * Total Snapshots Created
     */
    total_snapshots_created: number;
    /**
     * Companies Succeeded
     */
    companies_succeeded: number;
    /**
     * Companies Failed
     */
    companies_failed: number;
    /**
     * Total Companies
     */
    total_companies: number;
};

/**
 * ScrapeRunSummary
 */
export type ScrapeRunSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Company Name
     */
    company_name: string;
    /**
     * Company Slug
     */
    company_slug: string;
    /**
     * Status
     */
    status: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Jobs Found
     */
    jobs_found: number;
    /**
     * Snapshots Created
     */
    snapshots_created: number;
    /**
     * Postings Closed
     */
    postings_closed: number;
};

/**
 * StageStatus
 */
export type StageStatus = {
    /**
     * Status
     */
    status: string;
    /**
     * Last Completed At
     */
    last_completed_at: string | null;
    /**
     * Current Run
     */
    current_run: ScrapeCurrentRun | EnrichCurrentRun | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Auth Uid
     */
    auth_uid: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * TriggerResponse
 */
export type CompgraphApiRoutesAggregationTriggerResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * TriggerResponse
 */
export type CompgraphApiRoutesEnrichTriggerResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ControlResponse
 */
export type CompgraphApiRoutesSchedulerControlResponse = {
    /**
     * Schedule Id
     */
    schedule_id: string;
    /**
     * Paused
     */
    paused: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * TriggerResponse
 */
export type CompgraphApiRoutesSchedulerTriggerResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ControlResponse
 */
export type CompgraphApiRoutesScrapeControlResponse = {
    /**
     * Run Id
     */
    run_id: string;
    status: PipelineStatus;
    /**
     * Message
     */
    message: string;
};

/**
 * TriggerResponse
 */
export type CompgraphApiRoutesScrapeTriggerResponse = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Message
     */
    message: string;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TriggerScrapeApiV1ScrapeTriggerPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/trigger';
};

export type TriggerScrapeApiV1ScrapeTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesScrapeTriggerResponse;
};

export type TriggerScrapeApiV1ScrapeTriggerPostResponse = TriggerScrapeApiV1ScrapeTriggerPostResponses[keyof TriggerScrapeApiV1ScrapeTriggerPostResponses];

export type ScrapeStatusApiV1ScrapeStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/status';
};

export type ScrapeStatusApiV1ScrapeStatusGetResponses = {
    /**
     * Successful Response
     */
    200: PipelineRunResponse;
};

export type ScrapeStatusApiV1ScrapeStatusGetResponse = ScrapeStatusApiV1ScrapeStatusGetResponses[keyof ScrapeStatusApiV1ScrapeStatusGetResponses];

export type ScrapeStatusByIdApiV1ScrapeStatusRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/scrape/status/{run_id}';
};

export type ScrapeStatusByIdApiV1ScrapeStatusRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScrapeStatusByIdApiV1ScrapeStatusRunIdGetError = ScrapeStatusByIdApiV1ScrapeStatusRunIdGetErrors[keyof ScrapeStatusByIdApiV1ScrapeStatusRunIdGetErrors];

export type ScrapeStatusByIdApiV1ScrapeStatusRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: PipelineRunResponse;
};

export type ScrapeStatusByIdApiV1ScrapeStatusRunIdGetResponse = ScrapeStatusByIdApiV1ScrapeStatusRunIdGetResponses[keyof ScrapeStatusByIdApiV1ScrapeStatusRunIdGetResponses];

export type PauseScrapeApiV1ScrapePausePostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Run Id
         */
        run_id?: string | null;
    };
    url: '/api/v1/scrape/pause';
};

export type PauseScrapeApiV1ScrapePausePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseScrapeApiV1ScrapePausePostError = PauseScrapeApiV1ScrapePausePostErrors[keyof PauseScrapeApiV1ScrapePausePostErrors];

export type PauseScrapeApiV1ScrapePausePostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesScrapeControlResponse;
};

export type PauseScrapeApiV1ScrapePausePostResponse = PauseScrapeApiV1ScrapePausePostResponses[keyof PauseScrapeApiV1ScrapePausePostResponses];

export type ResumeScrapeApiV1ScrapeResumePostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Run Id
         */
        run_id?: string | null;
    };
    url: '/api/v1/scrape/resume';
};

export type ResumeScrapeApiV1ScrapeResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumeScrapeApiV1ScrapeResumePostError = ResumeScrapeApiV1ScrapeResumePostErrors[keyof ResumeScrapeApiV1ScrapeResumePostErrors];

export type ResumeScrapeApiV1ScrapeResumePostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesScrapeControlResponse;
};

export type ResumeScrapeApiV1ScrapeResumePostResponse = ResumeScrapeApiV1ScrapeResumePostResponses[keyof ResumeScrapeApiV1ScrapeResumePostResponses];

export type StopScrapeApiV1ScrapeStopPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Run Id
         */
        run_id?: string | null;
    };
    url: '/api/v1/scrape/stop';
};

export type StopScrapeApiV1ScrapeStopPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopScrapeApiV1ScrapeStopPostError = StopScrapeApiV1ScrapeStopPostErrors[keyof StopScrapeApiV1ScrapeStopPostErrors];

export type StopScrapeApiV1ScrapeStopPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesScrapeControlResponse;
};

export type StopScrapeApiV1ScrapeStopPostResponse = StopScrapeApiV1ScrapeStopPostResponses[keyof StopScrapeApiV1ScrapeStopPostResponses];

export type ForceStopScrapeApiV1ScrapeForceStopPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Run Id
         */
        run_id?: string | null;
    };
    url: '/api/v1/scrape/force-stop';
};

export type ForceStopScrapeApiV1ScrapeForceStopPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForceStopScrapeApiV1ScrapeForceStopPostError = ForceStopScrapeApiV1ScrapeForceStopPostErrors[keyof ForceStopScrapeApiV1ScrapeForceStopPostErrors];

export type ForceStopScrapeApiV1ScrapeForceStopPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesScrapeControlResponse;
};

export type ForceStopScrapeApiV1ScrapeForceStopPostResponse = ForceStopScrapeApiV1ScrapeForceStopPostResponses[keyof ForceStopScrapeApiV1ScrapeForceStopPostResponses];

export type ListScrapeRunsApiV1ScrapeRunsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scrape/runs';
};

export type ListScrapeRunsApiV1ScrapeRunsGetResponses = {
    /**
     * Successful Response
     */
    200: PipelineRunListResponse;
};

export type ListScrapeRunsApiV1ScrapeRunsGetResponse = ListScrapeRunsApiV1ScrapeRunsGetResponses[keyof ListScrapeRunsApiV1ScrapeRunsGetResponses];

export type TriggerPass1ApiV1EnrichPass1TriggerPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/enrich/pass1/trigger';
};

export type TriggerPass1ApiV1EnrichPass1TriggerPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesEnrichTriggerResponse;
};

export type TriggerPass1ApiV1EnrichPass1TriggerPostResponse = TriggerPass1ApiV1EnrichPass1TriggerPostResponses[keyof TriggerPass1ApiV1EnrichPass1TriggerPostResponses];

export type TriggerPass2ApiV1EnrichPass2TriggerPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/enrich/pass2/trigger';
};

export type TriggerPass2ApiV1EnrichPass2TriggerPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesEnrichTriggerResponse;
};

export type TriggerPass2ApiV1EnrichPass2TriggerPostResponse = TriggerPass2ApiV1EnrichPass2TriggerPostResponses[keyof TriggerPass2ApiV1EnrichPass2TriggerPostResponses];

export type TriggerFullApiV1EnrichTriggerPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/enrich/trigger';
};

export type TriggerFullApiV1EnrichTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesEnrichTriggerResponse;
};

export type TriggerFullApiV1EnrichTriggerPostResponse = TriggerFullApiV1EnrichTriggerPostResponses[keyof TriggerFullApiV1EnrichTriggerPostResponses];

export type EnrichStatusApiV1EnrichStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/enrich/status';
};

export type EnrichStatusApiV1EnrichStatusGetResponses = {
    /**
     * Successful Response
     */
    200: EnrichmentRunResponse;
};

export type EnrichStatusApiV1EnrichStatusGetResponse = EnrichStatusApiV1EnrichStatusGetResponses[keyof EnrichStatusApiV1EnrichStatusGetResponses];

export type EnrichStatusByIdApiV1EnrichStatusRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/enrich/status/{run_id}';
};

export type EnrichStatusByIdApiV1EnrichStatusRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EnrichStatusByIdApiV1EnrichStatusRunIdGetError = EnrichStatusByIdApiV1EnrichStatusRunIdGetErrors[keyof EnrichStatusByIdApiV1EnrichStatusRunIdGetErrors];

export type EnrichStatusByIdApiV1EnrichStatusRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: EnrichmentRunResponse;
};

export type EnrichStatusByIdApiV1EnrichStatusRunIdGetResponse = EnrichStatusByIdApiV1EnrichStatusRunIdGetResponses[keyof EnrichStatusByIdApiV1EnrichStatusRunIdGetResponses];

export type SchedulerStatusApiV1SchedulerStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/scheduler/status';
};

export type SchedulerStatusApiV1SchedulerStatusGetResponses = {
    /**
     * Successful Response
     */
    200: SchedulerStatusResponse;
};

export type SchedulerStatusApiV1SchedulerStatusGetResponse = SchedulerStatusApiV1SchedulerStatusGetResponses[keyof SchedulerStatusApiV1SchedulerStatusGetResponses];

export type TriggerJobApiV1SchedulerJobsJobIdTriggerPostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/scheduler/jobs/{job_id}/trigger';
};

export type TriggerJobApiV1SchedulerJobsJobIdTriggerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerJobApiV1SchedulerJobsJobIdTriggerPostError = TriggerJobApiV1SchedulerJobsJobIdTriggerPostErrors[keyof TriggerJobApiV1SchedulerJobsJobIdTriggerPostErrors];

export type TriggerJobApiV1SchedulerJobsJobIdTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesSchedulerTriggerResponse;
};

export type TriggerJobApiV1SchedulerJobsJobIdTriggerPostResponse = TriggerJobApiV1SchedulerJobsJobIdTriggerPostResponses[keyof TriggerJobApiV1SchedulerJobsJobIdTriggerPostResponses];

export type PauseJobApiV1SchedulerJobsJobIdPausePostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/scheduler/jobs/{job_id}/pause';
};

export type PauseJobApiV1SchedulerJobsJobIdPausePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PauseJobApiV1SchedulerJobsJobIdPausePostError = PauseJobApiV1SchedulerJobsJobIdPausePostErrors[keyof PauseJobApiV1SchedulerJobsJobIdPausePostErrors];

export type PauseJobApiV1SchedulerJobsJobIdPausePostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesSchedulerControlResponse;
};

export type PauseJobApiV1SchedulerJobsJobIdPausePostResponse = PauseJobApiV1SchedulerJobsJobIdPausePostResponses[keyof PauseJobApiV1SchedulerJobsJobIdPausePostResponses];

export type ResumeJobApiV1SchedulerJobsJobIdResumePostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/scheduler/jobs/{job_id}/resume';
};

export type ResumeJobApiV1SchedulerJobsJobIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumeJobApiV1SchedulerJobsJobIdResumePostError = ResumeJobApiV1SchedulerJobsJobIdResumePostErrors[keyof ResumeJobApiV1SchedulerJobsJobIdResumePostErrors];

export type ResumeJobApiV1SchedulerJobsJobIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesSchedulerControlResponse;
};

export type ResumeJobApiV1SchedulerJobsJobIdResumePostResponse = ResumeJobApiV1SchedulerJobsJobIdResumePostResponses[keyof ResumeJobApiV1SchedulerJobsJobIdResumePostResponses];

export type PipelineRunsApiV1PipelineRunsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pipeline/runs';
};

export type PipelineRunsApiV1PipelineRunsGetResponses = {
    /**
     * Successful Response
     */
    200: PipelineRunsResponse;
};

export type PipelineRunsApiV1PipelineRunsGetResponse = PipelineRunsApiV1PipelineRunsGetResponses[keyof PipelineRunsApiV1PipelineRunsGetResponses];

export type PipelineStatusApiV1PipelineStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/pipeline/status';
};

export type PipelineStatusApiV1PipelineStatusGetResponses = {
    /**
     * Successful Response
     */
    200: PipelineStatusResponse;
};

export type PipelineStatusApiV1PipelineStatusGetResponse = PipelineStatusApiV1PipelineStatusGetResponses[keyof PipelineStatusApiV1PipelineStatusGetResponses];

export type GetVelocityApiV1AggregationVelocityGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/v1/aggregation/velocity';
};

export type GetVelocityApiV1AggregationVelocityGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVelocityApiV1AggregationVelocityGetError = GetVelocityApiV1AggregationVelocityGetErrors[keyof GetVelocityApiV1AggregationVelocityGetErrors];

export type GetVelocityApiV1AggregationVelocityGetResponses = {
    /**
     * Response Get Velocity Api V1 Aggregation Velocity Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetVelocityApiV1AggregationVelocityGetResponse = GetVelocityApiV1AggregationVelocityGetResponses[keyof GetVelocityApiV1AggregationVelocityGetResponses];

export type GetBrandTimelineApiV1AggregationBrandTimelineGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/aggregation/brand-timeline';
};

export type GetBrandTimelineApiV1AggregationBrandTimelineGetResponses = {
    /**
     * Response Get Brand Timeline Api V1 Aggregation Brand Timeline Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetBrandTimelineApiV1AggregationBrandTimelineGetResponse = GetBrandTimelineApiV1AggregationBrandTimelineGetResponses[keyof GetBrandTimelineApiV1AggregationBrandTimelineGetResponses];

export type GetPayBenchmarksApiV1AggregationPayBenchmarksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/aggregation/pay-benchmarks';
};

export type GetPayBenchmarksApiV1AggregationPayBenchmarksGetResponses = {
    /**
     * Response Get Pay Benchmarks Api V1 Aggregation Pay Benchmarks Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetPayBenchmarksApiV1AggregationPayBenchmarksGetResponse = GetPayBenchmarksApiV1AggregationPayBenchmarksGetResponses[keyof GetPayBenchmarksApiV1AggregationPayBenchmarksGetResponses];

export type GetLifecycleApiV1AggregationLifecycleGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/aggregation/lifecycle';
};

export type GetLifecycleApiV1AggregationLifecycleGetResponses = {
    /**
     * Response Get Lifecycle Api V1 Aggregation Lifecycle Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetLifecycleApiV1AggregationLifecycleGetResponse = GetLifecycleApiV1AggregationLifecycleGetResponses[keyof GetLifecycleApiV1AggregationLifecycleGetResponses];

export type GetChurnSignalsApiV1AggregationChurnSignalsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/aggregation/churn-signals';
};

export type GetChurnSignalsApiV1AggregationChurnSignalsGetResponses = {
    /**
     * Response Get Churn Signals Api V1 Aggregation Churn Signals Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetChurnSignalsApiV1AggregationChurnSignalsGetResponse = GetChurnSignalsApiV1AggregationChurnSignalsGetResponses[keyof GetChurnSignalsApiV1AggregationChurnSignalsGetResponses];

export type GetCoverageGapsApiV1AggregationCoverageGapsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/aggregation/coverage-gaps';
};

export type GetCoverageGapsApiV1AggregationCoverageGapsGetResponses = {
    /**
     * Response Get Coverage Gaps Api V1 Aggregation Coverage Gaps Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetCoverageGapsApiV1AggregationCoverageGapsGetResponse = GetCoverageGapsApiV1AggregationCoverageGapsGetResponses[keyof GetCoverageGapsApiV1AggregationCoverageGapsGetResponses];

export type GetAgencyOverlapApiV1AggregationAgencyOverlapGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/aggregation/agency-overlap';
};

export type GetAgencyOverlapApiV1AggregationAgencyOverlapGetResponses = {
    /**
     * Response Get Agency Overlap Api V1 Aggregation Agency Overlap Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetAgencyOverlapApiV1AggregationAgencyOverlapGetResponse = GetAgencyOverlapApiV1AggregationAgencyOverlapGetResponses[keyof GetAgencyOverlapApiV1AggregationAgencyOverlapGetResponses];

export type TriggerAggregationApiV1AggregationTriggerPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/aggregation/trigger';
};

export type TriggerAggregationApiV1AggregationTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: CompgraphApiRoutesAggregationTriggerResponse;
};

export type TriggerAggregationApiV1AggregationTriggerPostResponse = TriggerAggregationApiV1AggregationTriggerPostResponses[keyof TriggerAggregationApiV1AggregationTriggerPostResponses];

export type ListCompaniesApiV1CompaniesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/companies';
};

export type ListCompaniesApiV1CompaniesGetResponses = {
    /**
     * Response List Companies Api V1 Companies Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ListCompaniesApiV1CompaniesGetResponse = ListCompaniesApiV1CompaniesGetResponses[keyof ListCompaniesApiV1CompaniesGetResponses];

export type ListPostingsApiV1PostingsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Company Id
         */
        company_id?: string | null;
        /**
         * Is Active
         */
        is_active?: boolean | null;
        /**
         * Role Archetype
         */
        role_archetype?: string | null;
        /**
         * Sort By
         */
        sort_by?: string;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/postings';
};

export type ListPostingsApiV1PostingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPostingsApiV1PostingsGetError = ListPostingsApiV1PostingsGetErrors[keyof ListPostingsApiV1PostingsGetErrors];

export type ListPostingsApiV1PostingsGetResponses = {
    /**
     * Successful Response
     */
    200: PostingListResponse;
};

export type ListPostingsApiV1PostingsGetResponse = ListPostingsApiV1PostingsGetResponses[keyof ListPostingsApiV1PostingsGetResponses];

export type GetPostingApiV1PostingsPostingIdGetData = {
    body?: never;
    path: {
        /**
         * Posting Id
         */
        posting_id: string;
    };
    query?: never;
    url: '/api/v1/postings/{posting_id}';
};

export type GetPostingApiV1PostingsPostingIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostingApiV1PostingsPostingIdGetError = GetPostingApiV1PostingsPostingIdGetErrors[keyof GetPostingApiV1PostingsPostingIdGetErrors];

export type GetPostingApiV1PostingsPostingIdGetResponses = {
    /**
     * Successful Response
     */
    200: PostingDetailResponse;
};

export type GetPostingApiV1PostingsPostingIdGetResponse = GetPostingApiV1PostingsPostingIdGetResponses[keyof GetPostingApiV1PostingsPostingIdGetResponses];

export type GetCorpusApiV1EvalCorpusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eval/corpus';
};

export type GetCorpusApiV1EvalCorpusGetResponses = {
    /**
     * Response Get Corpus Api V1 Eval Corpus Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetCorpusApiV1EvalCorpusGetResponse = GetCorpusApiV1EvalCorpusGetResponses[keyof GetCorpusApiV1EvalCorpusGetResponses];

export type GetRunsApiV1EvalRunsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eval/runs';
};

export type GetRunsApiV1EvalRunsGetResponses = {
    /**
     * Response Get Runs Api V1 Eval Runs Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetRunsApiV1EvalRunsGetResponse = GetRunsApiV1EvalRunsGetResponses[keyof GetRunsApiV1EvalRunsGetResponses];

export type CreateRunApiV1EvalRunsPostData = {
    body: RunCreate;
    path?: never;
    query?: never;
    url: '/api/v1/eval/runs';
};

export type CreateRunApiV1EvalRunsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRunApiV1EvalRunsPostError = CreateRunApiV1EvalRunsPostErrors[keyof CreateRunApiV1EvalRunsPostErrors];

export type CreateRunApiV1EvalRunsPostResponses = {
    /**
     * Response Create Run Api V1 Eval Runs Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type CreateRunApiV1EvalRunsPostResponse = CreateRunApiV1EvalRunsPostResponses[keyof CreateRunApiV1EvalRunsPostResponses];

export type DeleteRunApiV1EvalRunsRunIdDeleteData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/eval/runs/{run_id}';
};

export type DeleteRunApiV1EvalRunsRunIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRunApiV1EvalRunsRunIdDeleteError = DeleteRunApiV1EvalRunsRunIdDeleteErrors[keyof DeleteRunApiV1EvalRunsRunIdDeleteErrors];

export type DeleteRunApiV1EvalRunsRunIdDeleteResponses = {
    /**
     * Response Delete Run Api V1 Eval Runs  Run Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DeleteRunApiV1EvalRunsRunIdDeleteResponse = DeleteRunApiV1EvalRunsRunIdDeleteResponses[keyof DeleteRunApiV1EvalRunsRunIdDeleteResponses];

export type GetRunApiV1EvalRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/eval/runs/{run_id}';
};

export type GetRunApiV1EvalRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunApiV1EvalRunsRunIdGetError = GetRunApiV1EvalRunsRunIdGetErrors[keyof GetRunApiV1EvalRunsRunIdGetErrors];

export type GetRunApiV1EvalRunsRunIdGetResponses = {
    /**
     * Response Get Run Api V1 Eval Runs  Run Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRunApiV1EvalRunsRunIdGetResponse = GetRunApiV1EvalRunsRunIdGetResponses[keyof GetRunApiV1EvalRunsRunIdGetResponses];

export type GetRunResultsApiV1EvalRunsRunIdResultsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/eval/runs/{run_id}/results';
};

export type GetRunResultsApiV1EvalRunsRunIdResultsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunResultsApiV1EvalRunsRunIdResultsGetError = GetRunResultsApiV1EvalRunsRunIdResultsGetErrors[keyof GetRunResultsApiV1EvalRunsRunIdResultsGetErrors];

export type GetRunResultsApiV1EvalRunsRunIdResultsGetResponses = {
    /**
     * Response Get Run Results Api V1 Eval Runs  Run Id  Results Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetRunResultsApiV1EvalRunsRunIdResultsGetResponse = GetRunResultsApiV1EvalRunsRunIdResultsGetResponses[keyof GetRunResultsApiV1EvalRunsRunIdResultsGetResponses];

export type GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/eval/runs/{run_id}/field-accuracy';
};

export type GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetError = GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetErrors[keyof GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetErrors];

export type GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetResponses = {
    /**
     * Response Get Run Field Accuracy Api V1 Eval Runs  Run Id  Field Accuracy Get
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetResponse = GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetResponses[keyof GetRunFieldAccuracyApiV1EvalRunsRunIdFieldAccuracyGetResponses];

export type GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/eval/runs/{run_id}/field-reviews';
};

export type GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetError = GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetErrors[keyof GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetErrors];

export type GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetResponses = {
    /**
     * Response Get Run Field Reviews Api V1 Eval Runs  Run Id  Field Reviews Get
     *
     * Successful Response
     */
    200: {
        [key: string]: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetResponse = GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetResponses[keyof GetRunFieldReviewsApiV1EvalRunsRunIdFieldReviewsGetResponses];

export type GetRunProgressApiV1EvalRunsRunIdProgressGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/eval/runs/{run_id}/progress';
};

export type GetRunProgressApiV1EvalRunsRunIdProgressGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunProgressApiV1EvalRunsRunIdProgressGetError = GetRunProgressApiV1EvalRunsRunIdProgressGetErrors[keyof GetRunProgressApiV1EvalRunsRunIdProgressGetErrors];

export type GetRunProgressApiV1EvalRunsRunIdProgressGetResponses = {
    /**
     * Response Get Run Progress Api V1 Eval Runs  Run Id  Progress Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRunProgressApiV1EvalRunsRunIdProgressGetResponse = GetRunProgressApiV1EvalRunsRunIdProgressGetResponses[keyof GetRunProgressApiV1EvalRunsRunIdProgressGetResponses];

export type GetLeaderboardDataApiV1EvalLeaderboardDataGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eval/leaderboard-data';
};

export type GetLeaderboardDataApiV1EvalLeaderboardDataGetResponses = {
    /**
     * Response Get Leaderboard Data Api V1 Eval Leaderboard Data Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetLeaderboardDataApiV1EvalLeaderboardDataGetResponse = GetLeaderboardDataApiV1EvalLeaderboardDataGetResponses[keyof GetLeaderboardDataApiV1EvalLeaderboardDataGetResponses];

export type GetComparisonsApiV1EvalComparisonsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eval/comparisons';
};

export type GetComparisonsApiV1EvalComparisonsGetResponses = {
    /**
     * Response Get Comparisons Api V1 Eval Comparisons Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetComparisonsApiV1EvalComparisonsGetResponse = GetComparisonsApiV1EvalComparisonsGetResponses[keyof GetComparisonsApiV1EvalComparisonsGetResponses];

export type CreateComparisonApiV1EvalComparisonsPostData = {
    body: ComparisonCreate;
    path?: never;
    query?: never;
    url: '/api/v1/eval/comparisons';
};

export type CreateComparisonApiV1EvalComparisonsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateComparisonApiV1EvalComparisonsPostError = CreateComparisonApiV1EvalComparisonsPostErrors[keyof CreateComparisonApiV1EvalComparisonsPostErrors];

export type CreateComparisonApiV1EvalComparisonsPostResponses = {
    /**
     * Response Create Comparison Api V1 Eval Comparisons Post
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CreateComparisonApiV1EvalComparisonsPostResponse = CreateComparisonApiV1EvalComparisonsPostResponses[keyof CreateComparisonApiV1EvalComparisonsPostResponses];

export type GetEloApiV1EvalEloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eval/elo';
};

export type GetEloApiV1EvalEloGetResponses = {
    /**
     * Response Get Elo Api V1 Eval Elo Get
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetEloApiV1EvalEloGetResponse = GetEloApiV1EvalEloGetResponses[keyof GetEloApiV1EvalEloGetResponses];

export type DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteData = {
    body?: never;
    path: {
        /**
         * Result Id
         */
        result_id: string;
        /**
         * Field Name
         */
        field_name: string;
    };
    query?: never;
    url: '/api/v1/eval/field-reviews/{result_id}/{field_name}';
};

export type DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteError = DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteErrors[keyof DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteErrors];

export type DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteResponse = DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteResponses[keyof DeleteFieldReviewApiV1EvalFieldReviewsResultIdFieldNameDeleteResponses];

export type CreateFieldReviewApiV1EvalFieldReviewsPostData = {
    body: FieldReviewCreate;
    path?: never;
    query?: never;
    url: '/api/v1/eval/field-reviews';
};

export type CreateFieldReviewApiV1EvalFieldReviewsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFieldReviewApiV1EvalFieldReviewsPostError = CreateFieldReviewApiV1EvalFieldReviewsPostErrors[keyof CreateFieldReviewApiV1EvalFieldReviewsPostErrors];

export type CreateFieldReviewApiV1EvalFieldReviewsPostResponses = {
    /**
     * Response Create Field Review Api V1 Eval Field Reviews Post
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CreateFieldReviewApiV1EvalFieldReviewsPostResponse = CreateFieldReviewApiV1EvalFieldReviewsPostResponses[keyof CreateFieldReviewApiV1EvalFieldReviewsPostResponses];

export type ListModelsApiV1EvalModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/eval/models';
};

export type ListModelsApiV1EvalModelsGetResponses = {
    /**
     * Response List Models Api V1 Eval Models Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: string;
    }>;
};

export type ListModelsApiV1EvalModelsGetResponse = ListModelsApiV1EvalModelsGetResponses[keyof ListModelsApiV1EvalModelsGetResponses];

export type GetProgressApiV1EvalProgressTrackingIdGetData = {
    body?: never;
    path: {
        /**
         * Tracking Id
         */
        tracking_id: number;
    };
    query?: never;
    url: '/api/v1/eval/progress/{tracking_id}';
};

export type GetProgressApiV1EvalProgressTrackingIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProgressApiV1EvalProgressTrackingIdGetError = GetProgressApiV1EvalProgressTrackingIdGetErrors[keyof GetProgressApiV1EvalProgressTrackingIdGetErrors];

export type GetProgressApiV1EvalProgressTrackingIdGetResponses = {
    /**
     * Response Get Progress Api V1 Eval Progress  Tracking Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetProgressApiV1EvalProgressTrackingIdGetResponse = GetProgressApiV1EvalProgressTrackingIdGetResponses[keyof GetProgressApiV1EvalProgressTrackingIdGetResponses];

export type InviteUserApiV1AdminInvitePostData = {
    body: InviteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/invite';
};

export type InviteUserApiV1AdminInvitePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteUserApiV1AdminInvitePostError = InviteUserApiV1AdminInvitePostErrors[keyof InviteUserApiV1AdminInvitePostErrors];

export type InviteUserApiV1AdminInvitePostResponses = {
    /**
     * Successful Response
     */
    200: InviteResponse;
};

export type InviteUserApiV1AdminInvitePostResponse = InviteUserApiV1AdminInvitePostResponses[keyof InviteUserApiV1AdminInvitePostResponses];

export type ListUsersApiV1AdminUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type ListUsersApiV1AdminUsersGetResponses = {
    /**
     * Response List Users Api V1 Admin Users Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type ListUsersApiV1AdminUsersGetResponse = ListUsersApiV1AdminUsersGetResponses[keyof ListUsersApiV1AdminUsersGetResponses];

export type LegacyApiRedirectApiPathPostData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/{path}';
};

export type LegacyApiRedirectApiPathPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegacyApiRedirectApiPathPostError = LegacyApiRedirectApiPathPostErrors[keyof LegacyApiRedirectApiPathPostErrors];

export type LegacyApiRedirectApiPathPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LegacyApiRedirectApiPathPost2Data = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/{path}';
};

export type LegacyApiRedirectApiPathPost2Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegacyApiRedirectApiPathPost2Error = LegacyApiRedirectApiPathPost2Errors[keyof LegacyApiRedirectApiPathPost2Errors];

export type LegacyApiRedirectApiPathPost2Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LegacyApiRedirectApiPathPost3Data = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/{path}';
};

export type LegacyApiRedirectApiPathPost3Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegacyApiRedirectApiPathPost3Error = LegacyApiRedirectApiPathPost3Errors[keyof LegacyApiRedirectApiPathPost3Errors];

export type LegacyApiRedirectApiPathPost3Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LegacyApiRedirectApiPathPost4Data = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/{path}';
};

export type LegacyApiRedirectApiPathPost4Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegacyApiRedirectApiPathPost4Error = LegacyApiRedirectApiPathPost4Errors[keyof LegacyApiRedirectApiPathPost4Errors];

export type LegacyApiRedirectApiPathPost4Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LegacyApiRedirectApiPathPost5Data = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/{path}';
};

export type LegacyApiRedirectApiPathPost5Errors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LegacyApiRedirectApiPathPost5Error = LegacyApiRedirectApiPathPost5Errors[keyof LegacyApiRedirectApiPathPost5Errors];

export type LegacyApiRedirectApiPathPost5Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};
